// <auto-generated />
using System;
using EFCoreJsonApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreJsonApp.Migrations.JsonData
{
    [DbContext(typeof(JsonDataContext))]
    partial class JsonDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCoreJsonApp.Models.OrderWithOrderDetail.OrderWithOrderDetailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("OrderWithOrderDetails", (string)null);
                });

            modelBuilder.Entity("EFCoreJsonApp.Models.OrderWithOrderDetail.OrderWithOrderDetailEntity", b =>
                {
                    b.OwnsMany("EFCoreJsonApp.Models.OrderWithOrderDetail.OrderWithOrderDetailEntity.OrderDetailsJson#EFCoreJsonApp.Models.OrderWithOrderDetail.OrderDetailsJson", "OrderDetailsJson", b1 =>
                        {
                            b1.Property<Guid>("OrderWithOrderDetailEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("ItemName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<float>("Price")
                                .HasColumnType("real");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int");

                            b1.Property<float>("Total")
                                .HasColumnType("real");

                            b1.HasKey("OrderWithOrderDetailEntityId", "Id");

                            b1.ToTable("OrderWithOrderDetails", (string)null);

                            b1.ToJson("OrderDetailsJson");

                            b1.WithOwner()
                                .HasForeignKey("OrderWithOrderDetailEntityId");
                        });

                    b.Navigation("OrderDetailsJson");
                });
#pragma warning restore 612, 618
        }
    }
}
